### PR TITLE
Created include/pinmap/common.h to make it easier to configure boards

### PR DESCRIPTION
**Pull request by FozzTexx**
Make all pinmappings inherit from a common source to make it easier to see the differences and add new boards.

### CODE REVIEW

**Comment by mozzwald** [comment]
Every board variant can have a completely different pinmap than another. The way we handle this is create a new pinmap file in `include/pinmap/`, add a guard in the pinmap file (`#ifdef PINMAP_A2_D32`)  and add an include for it to `include/pinmap.h`.

**Comment by FozzTexx** [comment]
> Every board variant can have a completely different pinmap than another. The way we handle this is create a new pinmap file in `include/pinmap/`, add a guard in the pinmap file (`#ifdef PINMAP_A2_D32`) and add an include for it to `include/pinmap.h`.

They all have different pinmaps, but they have a *lot* in common. When I was first trying to get the Lolin D32 Pro setup for Apple II I of course started from the `a2_rev0.h` file but nothing seemed to work right. I kept trying to figure it out and comparing to the `iec-d32pro.h` but it was difficult to really see what was different between the two since there was so much duplication. Once I moved all the duplication into the `common.h` file it seemed clearer to me which pins I needed to configure for my specific board.

This PR *does not* add support for using the Lolin D32 Pro as an Apple II FujiNet, I wanted to keep the PR focused on a single change. I'll bring in the Lolin D32 Pro changes later.

**Comment by dillera** [comment]
Hello Fozz- I don't see a common.h inside the pinmap folders in this PR. Do you know where the common.h file is?

**Comment by markjfisher** [comment]
As Andy just said, I've checked out your branch, but I can't find the file `common.h` for the new common pinmaps. It's mentioned in the commit message, but not the in the commit files.

I tried compiling for IEC, but it's just erroring:

```
Compiling .pio/build/fujiapple-rev0/libd9e/hardware/fnWiFi.o
lib/bus/iwm/iwm_ll.cpp:587:37: error: 'PIN_SD_HOST_MOSI' was not declared in this scope
  587 |     esp_rom_gpio_connect_out_signal(PIN_SD_HOST_MOSI, spi_periph_signal[HSPI_HOST].spid_out, false, false);
      |                                     ^~~~~~~~~~~~~~~~
Compiling .pio/build/fujiapple-rev0/libd9e/hardware/keys.o
Compiling .pio/build/fujiapple-rev0/libd9e/hardware/led.o
lib/bus/iwm/iwm_ll.cpp: In member function 'void iwm_sp_ll::set_output_to_spi()':
lib/bus/iwm/iwm_ll.cpp:791:37: error: 'PIN_SD_HOST_MOSI' was not declared in this scope
  791 |     esp_rom_gpio_connect_out_signal(PIN_SD_HOST_MOSI, spi_periph_signal[HSPI_HOST].spid_out, false, false);
      |                                     ^~~~~~~~~~~~~~~~
lib/bus/iwm/iwm_ll.cpp: In member function 'void iwm_diskii_ll::set_output_to_rmt()':
lib/bus/iwm/iwm_ll.cpp:837:37: error: 'PIN_SD_HOST_MOSI' was not declared in this scope
  837 |     esp_rom_gpio_connect_out_signal(PIN_SD_HOST_MOSI, rmt_periph_signals.groups[0].channels[0].tx_sig, false, false);
      |                                     ^~~~~~~~~~~~~~~~
lib/bus/iwm/iwm_ll.cpp: In member function 'void iwm_diskii_ll::setup_rmt()':
lib/bus/iwm/iwm_ll.cpp:982:35: error: 'PIN_SD_HOST_MOSI' was not declared in this scope
  982 |     config.gpio_num = (gpio_num_t)PIN_SD_HOST_MOSI; //SP_WRDATA; // SP_SPI_FIX_PIN ; //PIN_SD_HOST_MOSI;
      |                                   ^~~~~~~~~~~~~~~~
*** [.pio/build/fujiapple-rev0/libaa5/bus/iwm/iwm_ll.o] Error 1
lib/hardware/fnUART.cpp: In member function 'void UARTManager::begin(int)':
lib/hardware/fnUART.cpp:88:14: error: 'PIN_UART0_RX' was not declared in this scope
   88 |         rx = PIN_UART0_RX;
      |              ^~~~~~~~~~~~
lib/hardware/fnUART.cpp:89:14: error: 'PIN_UART0_TX' was not declared in this scope
   89 |         tx = PIN_UART0_TX;
      |              ^~~~~~~~~~~~
lib/hardware/fnUART.cpp:93:14: error: 'PIN_UART1_RX' was not declared in this scope
   93 |         rx = PIN_UART1_RX;
      |              ^~~~~~~~~~~~
lib/hardware/fnUART.cpp:94:14: error: 'PIN_UART1_TX' was not declared in this scope
   94 |         tx = PIN_UART1_TX;
      |              ^~~~~~~~~~~~
lib/hardware/fnUART.cpp:99:14: error: 'PIN_UART2_RX' was not declared in this scope
   99 |         rx = PIN_UART2_RX;
      |              ^~~~~~~~~~~~
lib/hardware/fnUART.cpp:100:14: error: 'PIN_UART2_TX' was not declared in this scope
  100 |         tx = PIN_UART2_TX;
      |              ^~~~~~~~~~~~
*** [.pio/build/fujiapple-rev0/libd9e/hardware/fnUART.o] Error 1
lib/FileSystem/fnFsSD.cpp: In member function 'bool FileSystemSDFAT::start()':
lib/FileSystem/fnFsSD.cpp:653:24: error: 'PIN_SD_HOST_MOSI' was not declared in this scope
  653 |         .mosi_io_num = PIN_SD_HOST_MOSI,
      |                        ^~~~~~~~~~~~~~~~
lib/FileSystem/fnFsSD.cpp:654:24: error: 'PIN_SD_HOST_MISO' was not declared in this scope
  654 |         .miso_io_num = PIN_SD_HOST_MISO,
      |                        ^~~~~~~~~~~~~~~~
lib/FileSystem/fnFsSD.cpp:655:24: error: 'PIN_SD_HOST_SCK' was not declared in this scope
  655 |         .sclk_io_num = PIN_SD_HOST_SCK,
      |                        ^~~~~~~~~~~~~~~
lib/FileSystem/fnFsSD.cpp:668:27: error: 'PIN_SD_HOST_CS' was not declared in this scope
  668 |     slot_config.gpio_cs = PIN_SD_HOST_CS;
      |                           ^~~~~~~~~~~~~~
lib/hardware/led.cpp: In constructor 'LedManager::LedManager()':
lib/hardware/led.cpp:17:31: error: 'PIN_LED_WIFI' was not declared in this scope; did you mean 'LED_WIFI'?
   17 |     mLedPin[eLed::LED_WIFI] = PIN_LED_WIFI;
      |                               ^~~~~~~~~~~~
      |                               LED_WIFI
lib/hardware/led.cpp: In member function 'void LedManager::setup()':
lib/hardware/led.cpp:29:27: error: 'PIN_LED_WIFI' was not declared in this scope; did you mean 'LED_WIFI'?
   29 |     fnSystem.set_pin_mode(PIN_LED_WIFI, gpio_mode_t::GPIO_MODE_OUTPUT);
      |                           ^~~~~~~~~~~~
      |                           LED_WIFI
*** [.pio/build/fujiapple-rev0/libd9e/hardware/led.o] Error 1
lib/hardware/fnSystem.cpp: In member function 'void SystemManager::check_hardware_ver()':
lib/hardware/fnSystem.cpp:1189:27: error: 'PIN_BUTTON_C' was not declared in this scope; did you mean 'PIN_BUTTON_B'?
 1189 |     fnSystem.set_pin_mode(PIN_BUTTON_C, gpio_mode_t::GPIO_MODE_INPUT, SystemManager::pull_updown_t::PULL_UP);
      |                           ^~~~~~~~~~~~
      |                           PIN_BUTTON_B
*** [.pio/build/fujiapple-rev0/lib852/FileSystem/fnFsSD.o] Error 1
lib/hardware/fnSystem.cpp: At global scope:
lib/hardware/fnSystem.cpp:133:13: warning: 'void setup_card_detect(gpio_num_t)' defined but not used [-Wunused-function]
  133 | static void setup_card_detect(gpio_num_t pin)
      |             ^~~~~~~~~~~~~~~~~
*** [.pio/build/fujiapple-rev0/libd9e/hardware/fnSystem.o] Error 1
lib/hardware/keys.cpp:22:43: error: 'PIN_BUTTON_A' was not declared in this scope; did you mean 'PIN_BUTTON_B'?
   22 | static int mButtonPin[eKey::KEY_COUNT] = {PIN_BUTTON_A, PIN_BUTTON_B, PIN_BUTTON_C};
      |                                           ^~~~~~~~~~~~
      |                                           PIN_BUTTON_B
lib/hardware/keys.cpp:22:71: error: 'PIN_BUTTON_C' was not declared in this scope; did you mean 'PIN_BUTTON_B'?
   22 | static int mButtonPin[eKey::KEY_COUNT] = {PIN_BUTTON_A, PIN_BUTTON_B, PIN_BUTTON_C};
      |                                                                       ^~~~~~~~~~~~
      |                                                                       PIN_BUTTON_B
lib/hardware/keys.cpp: In member function 'void KeyManager::setup()':
lib/hardware/keys.cpp:44:34: error: 'PIN_BUTTON_A' was not declared in this scope; did you mean 'PIN_BUTTON_B'?
   44 |     mButtonPin[eKey::BUTTON_A] = PIN_BUTTON_A;
      |                                  ^~~~~~~~~~~~
      |                                  PIN_BUTTON_B
lib/hardware/keys.cpp:86:35: error: 'PIN_BUTTON_C' was not declared in this scope; did you mean 'PIN_BUTTON_B'?
   86 |             fnSystem.set_pin_mode(PIN_BUTTON_C, gpio_mode_t::GPIO_MODE_INPUT, SystemManager::pull_updown_t::PULL_UP);
      |                                   ^~~~~~~~~~~~
      |                                   PIN_BUTTON_B
lib/hardware/keys.cpp:88:35: error: 'PIN_BUTTON_C' was not declared in this scope; did you mean 'PIN_BUTTON_B'?
   88 |             fnSystem.set_pin_mode(PIN_BUTTON_C, gpio_mode_t::GPIO_MODE_INPUT, SystemManager::pull_updown_t::PULL_NONE);
      |                                   ^~~~~~~~~~~~
      |                                   PIN_BUTTON_B
*** [.pio/build/fujiapple-rev0/libd9e/hardware/keys.o] Error 1
```

**Comment by FozzTexx** [comment]
> Hello Fozz- I don't see a common.h inside the pinmap folders in this PR. Do you know where the common.h file is?

Whoops! I had it added in the other branch and somehow it didn't come over when I moved those commits to this new branch.

Fixed.

**Comment by markjfisher** [comment]
Can you please (as mentioned in the Dev guide) rebase your changes into a single commit rather than 3 commits?

The change does not need the history of all your changes. This is particularly relevant if this or any future PR includes internal merge requests you create (which should never be pushed back to main repo) to track upstream changes into your own repo.

Please see: https://github.com/FujiNetWIFI/fujinet-firmware/wiki/FujiNet-Development-Guidelines#reduce-the-commits-to-a-single-commit

**Comment by FozzTexx** [comment]
> Can you please (as mentioned in the Dev guide) rebase your changes into a single commit rather than 3 commits?

Done.

**Pull request closed without merging**
